server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 9905

spring:
  application:
    name: shop-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka
zuul:
  routes:
    shop-cas: /shop-cas/**
    shop-management: